version: '3.8'

services:
  irs-bot:
    build: .
    container_name: financial-tracker-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
